### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/foundations-group-project-tango-brigade#1]
# Story
As a developer, I want to have wireframes so that I know what the mockups of the website should be.

# AC
Mockups for each page with features drawn out

# Dev notes
- identify color scheme
- create rebranded logos

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/64911032-7bd4b000-d6e2-11e9-85b0-171e70a58a12.png)

**Comment by mariabrock** [comment]
![SJonly_nobackground](https://user-images.githubusercontent.com/54127296/64912415-826c2300-d6f4-11e9-88fb-6159d2fac4b6.png)
![TBonly_nobackground](https://user-images.githubusercontent.com/54127296/64912416-8304b980-d6f4-11e9-99ab-b2a6ca008f8c.png)

**Comment by mariabrock** [comment]
![SJ only](https://user-images.githubusercontent.com/54127296/64912417-8f891200-d6f4-11e9-950c-26e8bb85cc07.png)
![TB only](https://user-images.githubusercontent.com/54127296/64912418-8f891200-d6f4-11e9-9661-aa481997e51c.png)

**Comment by mariabrock** [comment]
![image](https://user-images.githubusercontent.com/54127296/65002190-3ff34380-d8b8-11e9-9ada-1cecb7a96b84.png)
