### ISSUE TITLE
About page title

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/foundations-group-project-tango-brigade#10]
# Story
As a user, when I load the About page, I want to see an About heading and a large image of the band. 

# AC
**WHEN** the about.html page loads
**THEN** a large image of the band is displayed
**AND** an About heading is placed on top of the image

# Dev notes
*the About h1 header will be contained in a div, which is assigned the band photo as the background photo. 
*photo to be the full width of the page (if possible)
*about not over their faces

**Comment by isischristopher** [comment]
https://www.spitrecords.co.uk/images/starjets/pic9.jpg

**Comment by isischristopher** [comment]
https://www.spitrecords.co.uk/images/starjets/pic1.jpg

**Comment by isischristopher** [comment]
![Screen Shot 2019-09-16 at 6 58 14 PM](https://user-images.githubusercontent.com/22875681/65001170-189a7780-d8b4-11e9-9abb-79c9d43929bc.png)
