### ISSUE TITLE
Tango Brigade Singles

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/foundations-group-project-tango-brigade#12]
# Story
As a user, I want to see the TangoBrigade singles so that I can see their discography.

# AC
**WHEN** the disc.html loads
**THEN** a card loads with the album art of the song per single
**AND** name of the song
**AND** length of the song

# Dev notes
- song information from discog
- album art information from discog 
- cards from bootstrap

**Comment by kelsey-21** [comment]
https://www.discogs.com/artist/2461612-Tango-Brigade

**Comment by mariabrock** [comment]
bootstrap card:
https://getbootstrap.com/docs/4.3/components/card/#horizontal

**Comment by mariabrock** [comment]
![image](https://user-images.githubusercontent.com/54127296/64912684-42a73a80-d6f8-11e9-953b-ab588dfd50a9.png)

**Comment by mariabrock** [comment]
![image](https://user-images.githubusercontent.com/54127296/64912692-59e62800-d6f8-11e9-8f60-625b5ccf55f9.png)

**Comment by zoeames** [comment]
what does the data structure look like for this?

**Comment by mariabrock** [comment]
const singles = [
   {
   imageUrl: "<img src = ' '></img>"
   albumTitle: "insert name here",
   }
   {
   imageUrl:  "<img src = ' '></img>"
   albumTitle: "insert name here",
   }
]

**Comment by mariabrock** [comment]
![image](https://user-images.githubusercontent.com/54127296/65002248-7d57d100-d8b8-11e9-81d8-ec1942d18c77.png)
