### ISSUE TITLE
Starjets Albums

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/foundations-group-project-tango-brigade#13]
# Story
As a user, I want to see the albums and years so that I know their discography.

# AC
**WHEN** the disc.html loads
**THEN** under the TB singles, SJ's album art shows in a horizontal row
**AND** the year shows below
**AND** if the album is clicked on, it links to discog

# Dev notes
- information from discog
- link to discog
- use bootsrap image card
- make each album image clickable and linked

**Comment by kelsey-21** [comment]
discog: https://www.discogs.com/artist/922611-Starjets#images/1935614

**Comment by mariabrock** [comment]
https://getbootstrap.com/docs/4.3/components/card/#images

**Comment by mariabrock** [comment]
album images:
https://img.discogs.com/KEAhNtDSz7x6xJcVgiuimJFG5Ng=/fit-in/600x605/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1321394-1564910928-8348.jpeg.jpg

https://img.discogs.com/xubyZAIv_YPT8t4J9Mx9VNc4ohw=/fit-in/600x593/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-3521390-1398544495-9162.jpeg.jpg

**Comment by mariabrock** [comment]
![image](https://user-images.githubusercontent.com/54127296/64912663-07a50700-d6f8-11e9-8d0a-fd2186152c90.png)

**Comment by mariabrock** [comment]
![image](https://user-images.githubusercontent.com/54127296/64912668-1b506d80-d6f8-11e9-9240-f3426158f4b7.png)

**Comment by zoeames** [comment]
what does the data look like for this?  sample album object please

**Comment by mariabrock** [comment]
const bandAlbums = [
{
imageUrl: ""
albumTitle: "insert name here",
}
{
imageUrl: ""
albumTitle: "insert name here",
}
]

**Comment by mariabrock** [comment]
![image](https://user-images.githubusercontent.com/54127296/65002271-9a8c9f80-d8b8-11e9-8a0e-7acb97a11793.png)
