### ISSUE TITLE
Starjets Singles

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/foundations-group-project-tango-brigade#14]
# Story
As a user, I want to see the StarJets singles so that I can see their discography.

# AC
**WHEN** the disc.html loads
**THEN** a card loads with the album art of the song per single
**AND** name of the song
**AND** length of the song

# Dev notes
- song information from discog
- album art information from discog 
- cards from bootstrap

**Comment by kelsey-21** [comment]
https://www.discogs.com/artist/922611-Starjets#images/1935614

**Comment by mariabrock** [comment]
![image](https://user-images.githubusercontent.com/54127296/64912633-bbf25d80-d6f7-11e9-8b83-1d6e9b6aff8d.png)

**Comment by zoeames** [comment]
what does the data look like for this?

**Comment by mariabrock** [comment]
const songList = [
{
imageUrl: ""
songName: "insert name here",
}
{
imageUrl: ""
songName: "insert name here",
}
]

**Comment by mariabrock** [comment]
![image](https://user-images.githubusercontent.com/54127296/65002302-c576f380-d8b8-11e9-9edf-b3af99c76654.png)
