### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/foundations-group-project-tango-brigade#3]
# Story
As a user, I want to see a dynamic band logo that tells me who the band is.

# AC
**WHEN** the index.html loads
**THEN** i should see the TANGO BRIGADE logo centered and large (about an inch tall)
**AND** when the other pages load
**THEN** the logo shrinks
**AND** slides to either top corner as user navigates
**AND** if user mouses/hovers over logo
**THEN** switches to STAR JET logo
**AND** clicking on the logo takes the user back to the homepage

# Dev notes
- if sliding does not work, KILL IT
- images should be stored in directory
- Maria created logos

**Comment by LaCollins** [comment]
Logo Home Page
![image](https://user-images.githubusercontent.com/51382883/65000700-3666dd00-d8b2-11e9-998e-e002ba895658.png)

**Comment by LaCollins** [comment]
Logo other pages
![image](https://user-images.githubusercontent.com/51382883/65000783-86de3a80-d8b2-11e9-9ff0-2f23a5c7cbe5.png)

**Comment by LaCollins** [comment]
GitHub does not support the uploading of SVG images. Logos stored locally.  Sample below:
![image](https://user-images.githubusercontent.com/51382883/65000830-bb51f680-d8b2-11e9-862f-f3be4a42c8b3.png)

**Comment by LaCollins** [comment]
Documentation for logo transforms:
https://css-tricks.com/almanac/properties/a/animation/
https://webdesignerwall.com/tutorials/easy-css-animation-transition-transforms
