### ISSUE TITLE
Navbar/Footer

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/foundations-group-project-tango-brigade#4]
# Story
As a user, I want to see a navbar at the bottom of the page, so that I can navigate

# AC
**WHEN** the page loads
**THEN** I see the navbar/footer
**AND** the links take me to the appropriate page
**AND** the social media links are included
**AND** it is sticky and has a black background

# Dev notes
- black background
- blue #80d6d1 (UNVISITED PAGES)
- lime green # cdff44 (PAGE YOU ARE ON)
- use bootstrap for the navbar
- use fontawesome for social icons (see comments)
- horizontal layout with socials on right side
- links on the left, copyright in middle, VERY SMALL

**Comment by kelsey-21** [comment]
font awesome socials:
- Twitter i class="fab fa-twitter"></i>
- Facebook i class="fab fa-facebook-f"></i>
- YouTube i class="fab fa-youtube"></i>
- Spotify i class="fab fa-spotify"></i>

**Comment by kelsey-21** [comment]
social hrefs:
- twitter: https://twitter.com/hashtag/starjets?lang=en
- facebook: https://www.facebook.com/Starjetsofficial/
- youtube: https://www.youtube.com/embed/9e35GQ5gDl0
- spotify: https://www.discogs.com/artist/922611-Starjets#images/1935614

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/65000624-de2fdb00-d8b1-11e9-8c6f-e36869ddb3a7.png)
