### ISSUE TITLE
Tour Email Form

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/foundations-group-project-tango-brigade#9]
# Story
As a user, I want to submit my email, so that I can sign up for the newsletter.

# AC
**WHEN** the page loads
**THEN** I can submit my email in the form
**AND** click submit
**AND** the form is replaced with a thank you for submitting message

# Dev notes
- link the button on the thank you message to the about.html page
- make sure the event listener for the about.html button is inside the thank you message printer

**Comment by kelsey-21** [comment]
https://mailchimp.com/help/add-a-signup-form-to-your-website/

**Comment by kelsey-21** [comment]
https://www.npmjs.com/package/html-form-send-email-via-google-script-without-server

**Comment by zoeames** [comment]
For this ticket do not save emails or use mailchimp  - to complicated.  just display a submit message

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/65000756-5e564080-d8b2-11e9-9691-93601faeab13.png)

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/65002475-9c0a9780-d8b9-11e9-9b2f-dfa9fb58315f.png)
